# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  database: nicolasdev_development
  pool: 5
  timeout: 5000


test: &TEST
  adapter: postgresql
  encoding: utf8
  database: nicolasdev_developtment
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: nicolasdev_production
  access_key_id: AKIAJXZAAVX5X6T3T34A
  secret_access_key: 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
  pool: 5
  timeout: 5000